# SPDX-License-Identifier: Unlicense

blank_issues_enabled: true
contact_links:
  - name: Main repoo
    url: 'https://gitlab.com/HiPhish/rainbow-delimiters.nvim'
    about: 'Upstream repository; you can also report bugs here on GitHub.'
